spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/aws
    username: root
    password: maria!db1
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: info
